Repository NordicSemiconductor/pc-nrfconnect-ppk, pull requests merged in 2024-03, with the labels that each got.

#419 Feat/update UI
  .vscode/launch.json
  .vscode/tasks.json
  Changelog.md
  package-lock.json
  package.json
  src/actions/deviceActions.ts
  src/components/Chart/AmpereChart.tsx
  src/components/Chart/Chart.tsx
  src/components/Chart/ChartTop.tsx
  src/components/SaveExport/ExportDialog.tsx
  src/components/SaveExport/ExportSelection.tsx
  src/components/SaveExport/SaveChoiceDialog.tsx
  src/components/SidePanel/CapVoltageSettings.tsx
  src/components/SidePanel/DigitalChannels.tsx
  src/components/SidePanel/DiskSpaceUsage.tsx
  src/components/SidePanel/DiskSpaceUsageBox.tsx
  src/components/SidePanel/DisplayOptions.tsx
  src/components/SidePanel/Gains.tsx
  src/components/SidePanel/LiveModeSettings.tsx
  src/components/SidePanel/LoadSave.tsx
  src/components/SidePanel/NumberWithUnitInput.tsx
  src/components/SidePanel/PowerMode.tsx
  src/components/SidePanel/SessionSettings.tsx
  src/components/SidePanel/SidePanel.tsx
  src/components/SidePanel/SpikeFilter.tsx
  src/components/SidePanel/StartStop.tsx
  src/components/SidePanel/TriggerSettings.tsx
  src/components/SidePanel/VoltageRegulator.tsx
  src/components/SidePanel/sidepanel.scss
  src/components/__tests__/StartStop.test.tsx
  src/globals.ts
  src/index.tsx
  src/slices/appSlice.ts
  src/slices/chartSlice.ts
  src/slices/dataLoggerSlice.ts
  src/slices/gainsSlice.ts
  src/slices/voltageRegulatorSlice.ts
  src/usageDataActions.ts
  src/utils/duration.tsx
  src/utils/fileUtils.ts
  src/utils/panes.ts
  src/utils/persistentStore.ts
  src/utils/saveFileHandler.ts
Labels: doc required, ui required

#423 Feat: update shared
  package-lock.json
  package.json
Labels: doc not required, ui not required

#425 Fix/minimap fails to load
  src/components/Chart/plugins/minimap.scroll.ts
  src/features/minimap/Minimap.tsx
  src/features/minimap/minimapSlice.ts
Labels: doc not required, ui not required

#426 Fix/buffering wrong page
  src/utils/FileBuffer.ts
  src/utils/WriteBuffer.ts
Labels: doc not required, ui not required

#428 Fix/zoom to selection
  src/components/Chart/Chart.tsx
  src/hooks/useLazyInitializedRef.ts
Labels: doc not required, ui not required

#429 Fix: prevent scrolling on chrt to sroll page and preven srolling out …
  src/components/Chart/plugins/chart.zoomPan.ts
Labels: doc not required, ui not required

#430 Fix: force cog wheel to stick to bar and not float when scrolling
  src/components/Chart/ChartTop.tsx
Labels: doc not required, ui not required

#431 Feat: change dir default to previously used dir
  src/components/SidePanel/SessionSettings.tsx
  src/utils/fileUtils.ts
Labels: doc not required, ui not required

#432 Fix: on scope mode unsaved state should only be set if we get a trigger
  src/actions/deviceActions.ts
Labels: doc not required, ui not required

#433 Fix: csv export
  src/actions/exportChartAction.ts
Labels: doc not required, ui not required

#434 Fix: copy last byte when processing triggers
  src/actions/deviceActions.ts
Labels: doc not required, ui not required

#435 Fix/trigger lagg
  src/actions/deviceActions.ts
  src/components/SidePanel/StartStop.tsx
  src/components/SidePanel/TriggerSettings.tsx
  src/slices/triggerSlice.ts
  src/utils/persistentStore.ts
Labels: doc not required, ui not required

#436 fix: force min to be 1 unless specifed in log mode
  src/components/Chart/AmpereChart.tsx
Labels: doc not required, ui not required

#437 Feat: update shared
  package-lock.json
  package.json
Labels: doc not required, ui not required

#438 Update nrfutil device
  package.json
Labels: doc not required, ui not required

#439 Fix: session files deleted wile conform dialog to close is still active
  src/utils/FileBuffer.ts
Labels: doc not required, ui not required

#440 fix: csv export
  src/actions/exportChartAction.ts
  src/globals.ts
Labels: doc not required, ui not required

#441 Fix/loading short files auto zoom
  src/actions/fileActions.ts
  src/slices/chartSlice.ts
Labels: doc not required, ui not required

#442 Fix: request a rerender chart when values change
  src/components/Chart/Chart.tsx
Labels: doc not required, ui not required

#443 fix: update link to troubleshooting
  src/device/serialDevice.ts
Labels: doc not required, ui not required

#444 Release 4.3.0 changelog edits
  Changelog.md
Labels: doc required, ui not required

#447 Feat: improve telemetry
  src/components/SidePanel/StartStop.tsx
Labels: doc not required, ui not required

#415 doc: update overview
  README.md
  doc/docs/index.md
  doc/docs/overview.md
  doc/docs/revision_history.md
  doc/docs/screenshots/data-logger-ampere-mode.png
  doc/docs/screenshots/minimap_live_view_gif.gif
  doc/docs/screenshots/ppk1/ppk1_data_logger_view.png
  doc/docs/screenshots/ppk1/ppk1_data_logger_view_magnify_power.png
  doc/docs/screenshots/ppk1/ppk1_real_time_view.png
  doc/docs/screenshots/ppk2_advanced_gains.PNG
  doc/docs/screenshots/ppk2_advanced_session_data.PNG
  doc/docs/screenshots/ppk2_advanced_spike.PNG
  doc/docs/screenshots/ppk2_advanced_voltage.PNG
  doc/docs/screenshots/ppk2_chart.PNG
  doc/docs/screenshots/ppk2_chart_settings.PNG
  doc/docs/screenshots/ppk2_device_panel_display_options.PNG
  doc/docs/screenshots/ppk2_device_panel_mode.png
  doc/docs/screenshots/ppk2_device_panel_other_options.PNG
  doc/docs/screenshots/ppk2_device_panel_sampling_live.png
  doc/docs/screenshots/ppk2_device_panel_sampling_params.png
  doc/docs/screenshots/ppk2_device_panel_sampling_start.PNG
  doc/docs/screenshots/ppk2_device_panel_sampling_trigger.png
  doc/docs/screenshots/ppk2_device_panel_sampling_trigger_arrow.PNG
  doc/docs/screenshots/ppk2_digital_channels.PNG
  doc/docs/screenshots/ppk2_live_view.PNG
  doc/docs/screenshots/ppk2_logger_tab.PNG
  doc/docs/screenshots/ppk2_minimap.PNG
  doc/docs/screenshots/ppk2_scope_tab.PNG
  doc/docs/screenshots/ppk2_selection.PNG
  doc/docs/screenshots/ppk2_selection_zoom.PNG
  doc/docs/screenshots/ppk2_standard_view.png
  doc/docs/screenshots/ppk2_standard_view_connected.png
  doc/docs/screenshots/ppk2_temp_disk_data.png
  doc/docs/screenshots/ppk2_window.PNG
  doc/docs/screenshots/real-time-source-mode.png
  doc/docs/using_ppk_app.md
  resources/screenshot.png
  src/components/SidePanel/Instructions.tsx
Labels: doc required, documentation

#446 Fix: middel mouse button back to start
  src/components/Chart/plugins/chart.zoomPan.ts
Labels: doc required, ui not required
