Repository NordicSemiconductor/pc-nrfconnect-ppk, pull requests merged in 2024-02, with the labels that each got.

#399 Fix: hide trigger items when not needed
  src/components/Chart/AmpereChart.tsx
Labels: doc not required

#400 Fix: remove tooltip
  src/components/SidePanel/StartStop.tsx
Labels: doc not required

#401 Update package.json
  package.json
Labels: doc not required

#403 Fix: only read data up to timestamp from ppk file buffer
  src/utils/loadFileHandler.ts
Labels: doc not required

#404 Fix: unmount dialog when not visable
  src/components/SidePanel/SidePanel.tsx
  src/features/ProgressDialog/progressSlice.ts
Labels: doc not required

#405 Fix: limit end size to max width of minimap
  src/features/minimap/Minimap.tsx
Labels: doc not required

#406 Fix: live view state
  src/components/Chart/ChartTop.tsx
Labels: doc not required

#407 Feat: show first trigger
  src/actions/deviceActions.ts
Labels: doc not required

#402 doc: add documentation framework
  .github/workflows/zoomin-publish-dev.yml
  .github/workflows/zoomin-publish.yml
  .github/workflows/zoomin.yml
  doc/docs/index.md
  doc/docs/installing.md
  doc/docs/overview.md
  doc/docs/revision_history.md
  doc/docs/screenshots/data-logger-ampere-mode.png
  doc/docs/screenshots/ppk1_data_logger_view.png
  doc/docs/screenshots/ppk1_data_logger_view_magnify_power.png
  doc/docs/screenshots/ppk1_real_time_view.png
  doc/docs/screenshots/ppk2_about_tab.png
  doc/docs/screenshots/ppk2_standard_view.png
  doc/docs/screenshots/real-time-source-mode.png
  doc/docs/troubleshooting.md
  doc/docs/using_ppk_app.md
  doc/mkdocs.yml
  doc/troubleshooting.md
  doc/zoomin/custom.properties
  doc/zoomin/tags.yml
Labels: doc required, documentation

#408 Feat: Split Data logger and trigger
  src/actions/deviceActions.ts
  src/components/Chart/AmpereChart.tsx
  src/components/Chart/Chart.tsx
  src/components/Chart/ChartTop.tsx
  src/components/DataLogger/DataLogger.tsx
  src/components/SidePanel/SamplingModeSettings.tsx
  src/components/SidePanel/SidePanel.tsx
  src/components/SidePanel/StartStop.tsx
  src/index.tsx
  src/slices/dataLoggerSlice.ts
  src/utils/panes.ts
  src/utils/persistentStore.ts
Labels: doc not required

#409 Feat: merge buttons and show dialog
  src/components/SidePanel/SidePanel.tsx
  src/components/SidePanel/StartStop.tsx
  src/utils/persistentStore.ts
Labels: doc not required

#410 Feat: add addaptive unit to trigger level
  src/components/Chart/AmpereChart.tsx
  src/components/SidePanel/TriggerSettings.tsx
Labels: doc not required

#411 Fix/minor issues
  src/actions/deviceActions.ts
  src/components/Chart/AmpereChart.tsx
  src/components/SidePanel/TriggerSettings.tsx
Labels: doc not required

#413 Fix: consider FPS in responsive design
  src/components/Chart/ChartTop.tsx
Labels: doc not required

#414 Feat/improve chart rendering
  src/components/Chart/AmpereChart.tsx
  src/components/Chart/Chart.tsx
  src/globals.ts
Labels: doc not required

#416 Feat/UI improvments
  src/actions/deviceActions.ts
  src/actions/fileActions.ts
  src/components/Chart/AmpereChart.tsx
  src/components/Chart/Chart.tsx
  src/components/Chart/ChartTop.tsx
  src/components/SidePanel/DiskSpaceUsage.tsx
  src/components/SidePanel/DiskSpaceUsageBox.tsx
  src/components/SidePanel/DisplayOptions.tsx
  src/components/SidePanel/LiveModeSettings.tsx
  src/components/SidePanel/LoadSave.tsx
  src/components/SidePanel/SessionSettings.tsx
  src/components/SidePanel/SidePanel.tsx
  src/components/SidePanel/StartStop.tsx
  src/components/SidePanel/TriggerSettings.tsx
  src/components/__tests__/SidePanel.test.tsx
  src/components/__tests__/StartStop.test.tsx
  src/constants.ts
  src/device/abstractDevice.ts
  src/device/serialDevice.ts
  src/features/minimap/Minimap.tsx
  src/features/minimap/MinimapOptions.tsx
  src/globals.ts
  src/index.tsx
  src/slices/appSlice.ts
  src/slices/chartSlice.ts
  src/slices/dataLoggerSlice.ts
  src/utils/fileUtils.ts
  src/utils/loadFileHandler.ts
  src/utils/persistentStore.ts
Labels: doc not required

#417 Fix: update free space with interval
  src/components/SidePanel/DiskSpaceUsage.tsx
  src/components/SidePanel/LiveModeSettings.tsx
Labels: doc not required

#418 ci: use shared labels workflow
  .github/workflows/labels.yml
Labels: doc not required, ui not required
