Repository NordicSemiconductor/pc-nrfconnect-ppk, pull requests merged in 2025-07, with the labels that each got.

#481 Feat/select triggering edge
  Changelog.md
  package-lock.json
  package.json
  src/actions/deviceActions.ts
  src/components/SidePanel/DisplayOptions.tsx
  src/components/SidePanel/LiveModeSettings.tsx
  src/components/SidePanel/SamplingSettings.tsx
  src/components/SidePanel/SessionSettings.tsx
  src/components/SidePanel/SidePanel.tsx
  src/components/SidePanel/StartStop.tsx
  src/components/SidePanel/TriggerSettings/AnalogTriggerSettings.tsx
  src/components/SidePanel/TriggerSettings/DigitalTriggerSettings.tsx
  src/components/SidePanel/TriggerSettings/TriggerSettings.tsx
  src/components/__tests__/ExportDialog.test.tsx
  src/components/__tests__/SidePanel.test.tsx
  src/globals.ts
  src/slices/triggerSlice.ts
  src/utils/persistentStore.ts
Labels: doc required, ui required

#537 Update changelog
  Changelog.md
Labels: doc not required, ui not required

#540 doc: trigger settings and offset
  doc/docs/overview.md
  doc/docs/revision_history.md
  doc/docs/screenshots/ppk2_device_panel_sampling_live.png
  doc/docs/screenshots/ppk2_device_panel_sampling_trigger.png
  doc/docs/screenshots/ppk2_device_panel_trigger_settings_analog.png
  doc/docs/screenshots/ppk2_device_panel_trigger_settings_digital.png
Labels: documentation, ui required

#542 Add session to list before file load procedure & update it after
  src/features/recovery/SessionsListFileHandler.ts
  src/utils/loadFileHandler.ts
Labels: doc not required, ui not required

#543 Release 4.3.0 update date
  Changelog.md
Labels: doc not required, ui not required
